name: diana-faers
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.8
  - pandas>=2.0.0
  - numpy>=1.24.0
  - dask>=2023.5.0
  - vaex>=4.16.0
  - pyarrow>=12.0.0
  - tqdm>=4.65.0
  - requests>=2.31.0
  - numexpr>=2.8.4  # For optimized computations
  - pytables>=3.8.0  # For HDF5 support
  - python-snappy>=0.6.1  # For compression support
  - pip>=23.0.0
  - pip:
    - memory_profiler>=0.61.0  # For memory optimization analysis